### ISSUE TITLE
Undefined reference setup and loop in main.cpp

### ISSUE THREAD

**Issue by PiotrC1** [MCUdude/MightyCore#178]
Hi,
  after upgrading from 2.0.3 to 2.0.4 I got following compilation errors:

> Arduino:1.8.12 (Windows 7), Board:"ATmega644, Yes (UART0), Standard pinout, 644P / 644PA, BOD 2.7V, Enabled, External 16 MHz"
> C:\Users\USER\AppData\Local\Temp\ccv5HAzJ.ltrans0.ltrans.o: In function `main':
> C:\Users\USER\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.4\cores\MCUdude_corefiles/main.cpp:43: undefined reference to `setup'
> C:\Users\USER\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.4\cores\MCUdude_corefiles/main.cpp:46: undefined reference to `loop'
> collect2.exe: error: ld returned 1 exit status
> exit status 1

Any help appreciated.

Regards,
PiotrC1

**Comment by PiotrC1** [comment]
Sorry - my fault. In my sketch `setup()` and `loop()` were not defined.
